### ISSUE TITLE
Config package

### ISSUE THREAD

**Issue by sesh-kebab** [quintilesims/eks-sso#6]
Deemed as a bad pattern borrowed from existing projects of having a config package to store cli flags and environment variables.

Suggestions:
- remove the config package entirely and merge items from config package to main.

**Comment by sesh-kebab** [comment]
@zpatrick can you please propose a better design here.

**Comment by zpatrick** [comment]
@sesh-kebab I don't know if I can propose any better, I like your suggestion!

I think this changeset should ultimately include:
* limiting the env/cli configuration scope to main
* passing config values in main to other parts in the codebase as parameters (similar to DI)
* Clean up config validation in main
